# Generated by Django 3.2.7 on 2021-09-13 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ストア名')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('is_opened', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='スタッフ名')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staffs', to='django_graphene.store')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
    ]
